#+SETUPFILE: ../org-themes/theme-readtheorg.setup
#+OPTIONS: ^:nil

#+INCLUDE: "./header.org"



* 
flowVC required the data input to be  _velocity.bin, _coordinates.bin, _connectivity.bin, and _adjacency.bin files need to be created from the velocity data. For each of these files, the full file name should incldue a file prefix before the _ to create a descriptive file name. 
** Cordinates File
For an unstructured velocity data set, the _cordinates.bin is a binary file stored in the following order.
\begin{equation} 
n \; \underbrace{x_0\; y_0\; z_0}_{\text{node 0}} \underbrace{x_1\;  y_1 \; z_1}_{\text{node 1}} ....\; \underbrace{x_{n-1} \; y_{n-1}\; z_{n-1}}_{\text{node n-1}}
\end{equation}

*** Data Type
n(int): the number of points in the data set
$x_i, y_i, z_i$(double): The cordinates of each node

** Connectivity
The _connectivity.bin file contains the nodes that make up each element. For a tetrahedral mesh this results in 4 points per element.

 \begin{equation} 
    e\; \underbrace{i_0^0\; i_0^1\; i_0^2\; i_0^3}_{\text{element 0}} \underbrace{i_1^0\; i_1^1\; i_1^2\; i_1^3}_{\text{element 1}} ... \underbrace{i_{e-1}^0\; i_{e-1}^1\; i_{e-1}^2\; i_{e-1}^3}_{\text{element e-1}} 
 \end{equation}

*** Data Type
e(int): The number of elements in the data set
$i_i^j$ (int): The index of the jth point making ith element in the dataset

** Adjacency
The _adjacency.bin file contains the indices of the adacent elements that share a face with the current element. The number of the element is based on the order of the coordinates.bin file.

 \begin{equation} 
    e\; \underbrace{e_0^0\; e_0^1\; e_0^2\; e_0^3}_{\text{element 0}} \underbrace{e_1^0\; e_1^1\; e_1^2\; e_1^3}_{\text{element 1}} ... \underbrace{e_{e-1}^0\; e_{e-1}^1\; e_{e-1}^2\; e_{e-1}^3}_{\text{element e-1}} 
 \end{equation}

*** Data Type
e(int): The number of elements in the data set
$e_i^j$ (int): The index of the element that shares the j'th face for the ith element in the dataset. Note if the element face is not shared with another element (i.e. on the edge this is a -1)



