* flowVC

Flow Visualization Code forked from FlowPhysics/flowVC

[[https://github.com/bkm82/flowVC/actions][https://github.com/bkm82/flowVC/workflows/CI/badge.svg]]
[[https://github.com/bkm82/flowVC/actions][https://github.com/bkm82/flowVC/workflows/CD/badge.svg]]
[[https://codecov.io/gh/bkm82/flowVC][https://codecov.io/gh/bkm82/flowVC/graph/badge.svg?token=1U1152BG8T]]


Copyright 2013 Shadden Research Group. All rights reserved.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

** Installation

*** Automated Release
If you are on ubuntu, the code here can be ran directly using the compiled binary in the latest release. Otherwise follow the instructions below for building the source code from the source code .

*** Build From Source
To build the code from source the there are two options. The first option involved installing Ceedling and its dependencies. Alternativly, if you have docker, you can download the docker image with the dependencies all bundeled together. 

**** Ceedling
***** Dependencies
[[https://www.ruby-lang.org/en/][Ruby]] > v 3.0: A programing language used for Ceedling

[[https://github.com/ThrowTheSwitch/Ceedling][Ceedling]] : Ceedling is a Test-Centered Build System for C. It utilizes a collection of tools for testing (Unity) and mocking (CMock) 

***** Instalation
1. Install [[https://www.ruby-lang.org/en/][Ruby]] by refering to the ruby documentation for your operating system.

2. Install Ceedling gem from the RubyGems repository
    #+begin_src shell
     gem install ceedling
   #+end_src

4. Clone the repository
   #+begin_src shell
     https://github.com/bkm82/flowVC.git
     cd flowVC
   #+end_src
5. To compile and run all of the tests, run
   #+begin_src shell
     ceedling test:all
   #+end_src
6. To build the relese run

   #+begin_src shell
     ceedling release
   #+end_src
   
   this will create the ./build/release/flowVC.out executable that you can run.

**** Docker
Alternatly, if you dont want to install the tooling and would prefer to use a docker container you can do that

1. Install docker (outside the scope of this documentation)
2. Clone the repository
   #+begin_src shell
     https://github.com/bkm82/flowVC.git
     cd flowVC
   #+end_src
   
3. Pull the docker image from docker hub [[https://hub.docker.com/r/throwtheswitch/madsciencelab][madsciencelab]] 
   #+begin_src shell
     docker pull throwtheswitch/madsciencelab:latest
   #+end_src
4. Run the tests: if you are in the flowVC directory you can replace the <local project path> with a "." (without the quotes)
   #+begin_src shell
     docker run -it --rm -v <local project path>:/home/dev/project throwtheswitch/madsciencelab:latest
     ceedling test:all
   #+end_src
5. Build the executable
   #+begin_src shell
     docker run -it --rm -v <local project path>:/home/dev/project throwtheswitch/madsciencelab:latest
     ceedling release     
   #+end_src
6. This will create the ./build/release/flowVC.out executable. NOTE: as this was compiled using a linux (Ubuntu) docker container, this might not work if you are on another operating system. In that case you can run the command through the docker container (i.e.)
   #+begin_src shell
     docker run -it --rm -v .:/home/dev/project throwtheswitch/madsciencelab:latest
     .build/release/flowVC.out <input file>  
   #+end_src
   
**** Make
The third option is to compile the source code using the provided Make file, however this file is not currently part of the CI/CD pipeline so there may be compilation bugs. Issue reports and/or contributions are welcome
** Development Guidlines
*** Semantic Versioning:
This project intends to use a Trunk-Based Release with semantic versioning. Commit messages should follow [[https://www.conventionalcommits.org/en/v1.0.0/][conventional commits]]
#+begin_src shell
<type>[optional scope]: <description>
#+end_src

Where the type determines the version updates.

Valid types are fix, feat, BREAKING CHANGE, build, chore, ci, docs, style, refactor, perf, test


