* flowVC

Flow Visualization Code forked from FlowPhysics/flowVC

[[https://github.com/bkm82/flowVC/actions][https://github.com/bkm82/flowVC/actions/workflows/tests.yml/badge.svg]]
[[https://codecov.io/gh/bkm82/flowVC][https://codecov.io/gh/bkm82/flowVC/graph/badge.svg?token=1U1152BG8T]]


Copyright 2013 Shadden Research Group. All rights reserved.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

** Installation
*** Binaries
Currently this project does not have any pre-build binaries, so the code must be build from source. Reference the Development section below.
*** Development
**** Dependencies
[[https://www.ruby-lang.org/en/][Ruby]] > v 3.0: A programing language used for Ceedling

[[https://github.com/ThrowTheSwitch/Ceedling][Ceedling]] : A collection of tools for C project including Unity and CMock for testing

gcovr: a code coverage reporter

**** Instalation
1. Install [[https://www.ruby-lang.org/en/][Ruby]]

2. Install Ceedling gem from the RubyGems repository
    #+begin_src shell
     gem install ceedling
   #+end_src
3. Install gcovr
   #+begin_src shell
     sudo apt install gcovr
   #+end_src
4. Clone the repository
   #+begin_src shell
     https://github.com/bkm82/flowVC.git
     cd flowVC
   #+end_src
5. To compile and run all of the tests, run
   #+begin_src shell
     ceedling test:all
   #+end_src
6. To build the relese run

   #+begin_src shell
     ceedling release
   #+end_src
   this will create the ./build/release/flowVC.out executable
   

