---
name: Build Project

on:
  workflow_call:
  push:
    branches:
      - windows_build
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Set output file extension
    run: echo "OUTPUT_EXTENSION=$(if [ ${{ runner.os }} == 'Windows' ]; then echo 'exe'; else echo 'out'; fi)" >> $GITHUB_ENV

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Install Ceedling
      run: gem install ceedling

    - name: Run Tests
      run: ceedling release


    - name: Rename build binary
      shell: pwsh
      run: Move-Item -Path build/release/flowVC.out -Destination build/release/${{ runner.os}}.flowVC.$OUTPUT_EXTENSION

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}.flowVC.$OUTPUT_EXTENSION
        path: build/release/${{ runner.os}}.flowVC.$OUTPUT_EXTENSION
        overwrite: true
