---
name: Build Project

on:
  workflow_call:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build Release
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            release_suffix: out
          - os: windows-latest
            release_suffix: exe
          - os: macos-latest
            release_suffix: out
    runs-on: ${{ matrix.os }}
  
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Ceedling
      run: gem install ceedling

    - name: Build Release
      run: ceedling release


    - name: Rename build binary
      shell: pwsh
      run: Move-Item -Path build/release/flowVC.out -Destination build/release/flowVC.${{ matrix.release_suffix}}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: flowVC_${{ runner.os }}
        path: build/release/flowVC.${{ matrix.release_suffix}}
        overwrite: true
