---
name: CI

on:
  # Manually triggered testing
  workflow_dispatch:

  # Called from another work flow
  workflow_call:

  pull_request:
    branches:
      - main
      - master
  push:
    # Called from CD, prevents duplicate running
    branches-ignore:
      - main
      - master

jobs:
  build:
    name: Run Tests

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            release_suffix: out
          - os: windows-latest
            release_suffix: exe
          - os: macos-latest
            release_suffix: out
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Ceedling
        run: gem install ceedling

      - name: Run Tests
        run: ceedling gcov:all

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
