name: CI

on:
  # Manually triggered testing
  workflow_dispatch:
  push:
  # Check every PR to main
  pull_request:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run all Tests using Docker
        run: |
          docker run \
	  --interactive \
          --rm \
          -u $(id -u):$(id -g) \
          --volume .:/home/dev/project \
          throwtheswitch/madsciencelab-plugins:1.0.0 \
          ceedling gcov:all
         
      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}