name: CD

on:
  # Publish on every approved PR
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  check:
    name: check pr status
    runs-on: ubuntu-latest
    steps:
      - name: check if PR is merged
        uses: zmynx/github-actions/.github/actions/git/check-merge@feature/gha

  cd:
    name: build
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release using Docker
        run: |
          docker run \
          --interactive \
          --rm \
          -u $(id -u):$(id -g) \
          --volume .:/home/dev/project \
          throwtheswitch/madsciencelab-plugins:1.0.0 \
          ceedling release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flowVC.out
          path: ./build/artifacts/release/flowVC.out

      - name: Determine Release Info
        id: release
        uses: Fresa/trunk-based-release-versioning@main
      - run: echo "Release version: ${{ steps.release.outputs.version }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ORG_GH_ACCESS_TOKEN }}
          tag_name: ${{ steps.release.outputs.version }}
          files: |
            ./build/release/flowVC.out
          draft: true
          prerelease: true
          generate_release_notes: true

