name: CD

on:
  # Publish on every approved PR
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  check:
    name: check pr status
    runs-on: ubuntu-latest
    steps:
      - name: check if PR is merged
        uses: zmynx/github-actions/.github/actions/git/check-merge@feature/gha

  cd:
    name: build
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Release using Docker
        run: |
          docker run \
          --interactive \
          --rm \
          -u $(id -u):$(id -g) \
          --volume .:/home/dev/project \
          throwtheswitch/madsciencelab-plugins:1.0.0 \
          ceedling release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flowVC.out
          path: ./build/artifacts/release/flowVC.out
      - name: Bump version and push tag
        id: semantic
        uses: mathieudutour/github-tab-action@v6.1
        with:
          github_token: ${{ secrets.ORG_GH_ACCESS_TOKEN}}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/v*')
        with:
          token: ${{ secrets.ORG_GH_ACCESS_TOKEN }}
          tag_name: ${{ steps.semantic.outputs.new_tag }}
          draft: true
          prerelease: true
          generate_release_notes: true

