name: Tests

on:
  - push
  - pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Install Ceedling
      run: gem install ceedling
    - name: Install gcovr
      run: pip install gcovr
    - name: Run Unit tests
      run: ceedling gcov:all
    - name: check for coverage report
      run: ls -l ./build/artifacts/gcov/gcovr/
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./build/artifacts/gcov/gcovr/GcovCoverageCobertura.xml
        token: ${{ secrets.CODECOV_TOKEN }}